#!/usr/bin/env bash
set -euo pipefail
repo_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
cmake -S "$repo_dir" -B "$repo_dir/build" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_TESTING=ON
cmake --build "$repo_dir/build" --parallel 2
ctest --test-dir "$repo_dir/build" --output-on-failure
install -Dm755 "$repo_dir/build/omaflip" "$HOME/.local/lib/omaflip/omaflip"
